//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_SC
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_master
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email_id { get; set; }
        public string Password { get; set; }
        public int Mobile_no { get; set; }
    }
}
